[settings]
lockfile = true

[hooks]
postinstall = "~/.local/bin/refresh-zsh-completions"

[tool_alias]
claude = "github:anthropics/claude-code"

[tools]
actionlint = "latest"
atuin = "latest"
bat = "latest"
bitwarden = "latest"
carapace = "latest"
chezmoi = "latest"
claude = { version = "latest", exe = "claude" }
deno = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
glow = "latest"
hyperfine = "latest"
neovim = "latest"
sheldon = "latest"
shellcheck = "latest"
starship = "latest"
usage = "latest"
zellij = "latest"
zoxide = "latest"
