snippets:
  - name: update apt / mise / dotfiles
    keyword: up
    snippet: update
  - name: update and upgrade packages
    keyword: apt-up
    snippet: sudo apt update && sudo apt upgrade -y
  - name: benchmark
    keyword: benchmark
    snippet: hyperfine -w 5 -r 50 'zsh -i -c exit'
  - name: clip
    keyword: clip
    snippet: xclip -selection clipboard
  - name: relogin
    keyword: relogin
    snippet: exec $SHELL -l
  - name: reload
    keyword: reload
    snippet: exec $SHELL
  - name: mise
    keyword: m
    snippet: mise
  - name: eza
    keyword: l
    snippet: eza -lha --icons --group-directories-first
  - name: git
    keyword: g
    snippet: git
  - name: git push
    keyword: ps
    snippet: push
    context:
      lbuffer: ^git\s
  - name: git pull
    keyword: pl
    snippet: pull
    context:
      lbuffer: ^git\s
  - name: git checkout
    keyword: co
    snippet: checkout
    context:
      lbuffer: ^git\s
  - name: git branch
    keyword: br
    snippet: branch
    context:
      lbuffer: ^git\s
  - name: git status
    keyword: st
    snippet: status
    context:
      lbuffer: ^git\s
  - name: git switch
    keyword: sw
    snippet: switch
    context:
      lbuffer: ^git\s
  - name: git switch -c
    keyword: swc
    snippet: switch -c
    context:
      lbuffer: ^git\s
  - name: git switch -c feature/
    keyword: f
    snippet: feature/{{}}
    context:
      lbuffer: ^git\sswitch\s-c\s
  - name: git commit message
    keyword: cm
    snippet: commit -m '{{commit_message}}'
    context:
      lbuffer: ^git\s
  - name: chezmoi
    keyword: cz
    snippet: chezmoi
  - name: chezmoi apply
    keyword: a
    snippet: apply
    context:
      lbuffer: ^chezmoi\s
  - name: chezmoi update
    keyword: up
    snippet: update
    context:
      lbuffer: ^chezmoi\s
  - name: chezmoi status
    keyword: st
    snippet: git -- status
    context:
      lbuffer: ^chezmoi\s
  - name: chezmoi commit message
    keyword: cm
    snippet: git -- commit -m '{{commit_message}}'
    context:
      lbuffer: ^chezmoi\s
  - name: chezmoi add and commit message
    keyword: cma
    snippet: git -- commit -a -m '{{commit_message}}'
    context:
      lbuffer: ^chezmoi\s
  - name: pnpm
    keyword: p
    snippet: pnpm
